AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Api gateway for the application

Parameters:
  SpotifyApiLambda:
    Description: The arn of the lambda that calls spotify api
    Type: String
  Environment:
    Description: The environment where this resource is deployed
    Type: String

Resources:
  SpotifyIntegrationApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: SpotifyIntegrationAPI
      StageName: dev
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      Description: Api gateway for the application
      DisableExecuteApiEndpoint: False
      FailOnWarnings: False
      DefinitionBody:
        Fn:Transform:
          Name: "AWS::Include"
          Parameters:
            Location: ./api-definition.yml

  SpotifyApiLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SpotifyApiLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SpotifyIntegrationApiGateway}:${Environment}:POST/*"

Outputs:
  SpotifyIntegrationApiGateway:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Ref SpotifyIntegrationApiGateway
